<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentTableSeeder extends Seeder
{
    public function run()
    {
        // Data Profil (6 Data)
        DB::table('contents')->insert([
            [
                'title' => 'Profil Dinas Pariwisata Pemuda dan Olahraga Kabupaten Sijunjung',
                'slug' => 'profil-dinas-pariwisata',
                'content' => 'Dinas Pariwisata Pemuda dan Olahraga Kabupaten Sijunjung berperan dalam mengelola dan mengembangkan sektor pariwisata serta membina kegiatan olahraga di kabupaten ini.',
                'description_short' => 'Profil Dinas Pariwisata Pemuda dan Olahraga Kabupaten Sijunjung',
                'image' => 'uploads/profil-dinas.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Profil instansi pemerintah daerah',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Visi dan Misi Dinas Pariwisata',
                'slug' => 'visi-misi-dinas-pariwisata',
                'content' => 'Visi Dinas Pariwisata adalah meningkatkan daya tarik wisata di Kabupaten Sijunjung.',
                'description_short' => 'Visi dan Misi Dinas Pariwisata Kabupaten Sijunjung',
                'image' => 'uploads/visi-misi.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Visi dan Misi Dinas',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Struktur Organisasi Dinas Pariwisata',
                'slug' => 'struktur-organisasi-dinas-pariwisata',
                'content' => 'Struktur organisasi Dinas Pariwisata mencakup Kepala Dinas, Sekretaris, dan beberapa bidang.',
                'description_short' => 'Struktur Organisasi Dinas Pariwisata Kabupaten Sijunjung',
                'image' => 'uploads/struktur-organisasi.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Struktur Organisasi Dinas',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sejarah Dinas Pariwisata Sijunjung',
                'slug' => 'sejarah-dinas-pariwisata-sijunjung',
                'content' => 'Dinas Pariwisata Sijunjung berdiri pada tahun...',
                'description_short' => 'Sejarah berdirinya Dinas Pariwisata di Kabupaten Sijunjung.',
                'image' => 'uploads/sejarah-dinas.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Sejarah berdirinya Dinas',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tujuan Strategis Dinas Pariwisata',
                'slug' => 'tujuan-strategis-dinas-pariwisata',
                'content' => 'Tujuan strategis Dinas Pariwisata adalah meningkatkan kunjungan wisatawan.',
                'description_short' => 'Tujuan strategis Dinas Pariwisata Kabupaten Sijunjung',
                'image' => 'uploads/tujuan-strategis.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Tujuan Strategis Dinas',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sasaran Dinas Pariwisata Sijunjung',
                'slug' => 'sasaran-dinas-pariwisata-sijunjung',
                'content' => 'Sasaran dari program pariwisata adalah meningkatkan pengelolaan wisata.',
                'description_short' => 'Sasaran program Dinas Pariwisata Kabupaten Sijunjung.',
                'image' => 'uploads/sasaran-dinas.jpg',
                'type' => 'profil',
                'category_id' => null,
                'notes' => 'Sasaran program Dinas',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Data Berita (6 Data)
        DB::table('contents')->insert([
            [
                'title' => 'Festival Budaya Sijunjung',
                'slug' => 'festival-budaya-sijunjung',
                'content' => 'Festival Budaya Sijunjung kembali digelar untuk mempromosikan kekayaan budaya daerah.',
                'description_short' => 'Festival tahunan yang diadakan untuk mempromosikan budaya lokal.',
                'image' => 'uploads/berita/festival-budaya.jpg',
                'type' => 'berita',
                'category_id' => 2,
                'notes' => 'Berita terkait festival daerah',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Peresmian Objek Wisata Baru',
                'slug' => 'peresmian-objek-wisata-baru',
                'content' => 'Objek wisata baru di Kabupaten Sijunjung telah resmi dibuka.',
                'description_short' => 'Peresmian objek wisata baru yang menarik banyak wisatawan.',
                'image' => 'uploads/berita/peresmian-wisata.jpg',
                'type' => 'berita',
                'category_id' => 3,
                'notes' => 'Peresmian objek wisata',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lomba Olahraga Antar Sekolah',
                'slug' => 'lomba-olahraga-antar-sekolah',
                'content' => 'Lomba olahraga antar sekolah se-Kabupaten Sijunjung sukses dilaksanakan.',
                'description_short' => 'Lomba olahraga antar sekolah sukses dilaksanakan.',
                'image' => 'uploads/berita/lomba-olahraga.jpg',
                'type' => 'berita',
                'category_id' => 4,
                'notes' => 'Berita lomba olahraga',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pelatihan Pariwisata untuk Pemuda',
                'slug' => 'pelatihan-pariwisata-untuk-pemuda',
                'content' => 'Pelatihan pariwisata diadakan untuk pemuda Kabupaten Sijunjung.',
                'description_short' => 'Pelatihan pariwisata diadakan untuk pemuda setempat.',
                'image' => 'uploads/berita/pelatihan-pariwisata.jpg',
                'type' => 'berita',
                'category_id' => 5,
                'notes' => 'Pelatihan pariwisata',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Parade Budaya Sijunjung',
                'slug' => 'parade-budaya-sijunjung',
                'content' => 'Parade budaya menampilkan kesenian tradisional dari berbagai daerah di Kabupaten Sijunjung.',
                'description_short' => 'Parade budaya menampilkan kesenian tradisional.',
                'image' => 'uploads/berita/parade-budaya.jpg',
                'type' => 'berita',
                'category_id' => 6,
                'notes' => 'Parade budaya',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kunjungan Wisatawan Meningkat',
                'slug' => 'kunjungan-wisatawan-meningkat',
                'content' => 'Kunjungan wisatawan ke Kabupaten Sijunjung meningkat drastis tahun ini.',
                'description_short' => 'Kunjungan wisatawan meningkat di Sijunjung.',
                'image' => 'uploads/berita/kunjungan-wisatawan.jpg',
                'type' => 'berita',
                'category_id' => 2,
                'notes' => 'Berita kunjungan wisatawan',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Data Artikel (6 Data)
        DB::table('contents')->insert([
            [
                'title' => 'Potensi Wisata Alam di Sijunjung',
                'slug' => 'potensi-wisata-alam-sijunjung',
                'content' => 'Kabupaten Sijunjung memiliki banyak potensi wisata alam yang menarik untuk dikunjungi.',
                'description_short' => 'Potensi wisata alam di Sijunjung.',
                'image' => 'uploads/artikel/wisata-alam.jpg',
                'type' => 'artikel',
                'category_id' => 3,
                'notes' => 'Artikel tentang wisata alam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kuliner Khas Sijunjung',
                'slug' => 'kuliner-khas-sijunjung',
                'content' => 'Kuliner khas Sijunjung menawarkan rasa yang unik dan lezat.',
                'description_short' => 'Mengenal kuliner khas Sijunjung yang wajib dicoba.',
                'image' => 'uploads/artikel/kuliner-khas.jpg',
                'type' => 'artikel',
                'category_id' => 1,
                'notes' => 'Artikel tentang kuliner',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tips Berwisata di Sijunjung',
                'slug' => 'tips-berwisata-di-sijunjung',
                'content' => 'Tips berwisata di Sijunjung agar perjalanan Anda lebih menyenangkan dan aman.',
                'description_short' => 'Tips dan trik untuk berwisata di Sijunjung.',
                'image' => 'uploads/artikel/tips-berwisata.jpg',
                'type' => 'artikel',
                'category_id' => 1,
                'notes' => 'Artikel tips berwisata',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sejarah Wisata Sijunjung',
                'slug' => 'sejarah-wisata-sijunjung',
                'content' => 'Sejarah perkembangan wisata di Kabupaten Sijunjung sejak zaman dahulu.',
                'description_short' => 'Sejarah perkembangan wisata di Sijunjung.',
                'image' => 'uploads/artikel/sejarah-wisata.jpg',
                'type' => 'artikel',
                'category_id' => 4,
                'notes' => 'Artikel sejarah wisata',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Penginapan di Sijunjung',
                'slug' => 'penginapan-di-sijunjung',
                'content' => 'Berbagai pilihan penginapan di Sijunjung yang nyaman dan terjangkau.',
                'description_short' => 'Informasi penginapan terbaik di Sijunjung.',
                'image' => 'uploads/artikel/penginapan-sijunjung.jpg',
                'type' => 'artikel',
                'category_id' => 6,
                'notes' => 'Artikel tentang penginapan',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Event Tahunan di Sijunjung',
                'slug' => 'event-tahunan-sijunjung',
                'content' => 'Event tahunan di Sijunjung menjadi daya tarik tersendiri bagi wisatawan.',
                'description_short' => 'Event tahunan yang wajib dikunjungi di Sijunjung.',
                'image' => 'uploads/artikel/event-tahunan.jpg',
                'type' => 'artikel',
                'category_id' => 6,
                'notes' => 'Artikel tentang event tahunan',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
